USE [mpos_pollo_express_qa]
GO

/****** Object:  Table [dbo].[D_USUARIO_ASISTENCIA]    Script Date: 2020/11/05 10:11:23 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D_USUARIO_ASISTENCIA](
	[CODIGO_ASISTENCIA] [int] IDENTITY(1,1) NOT NULL,
	[EMPRESA] [int] NULL,
	[CODIGO_SUCURSAL] [int] NULL,
	[CODIGO_VENDEDOR] [int] NULL,
	[INICIO] [datetime] NULL,
	[FIN] [datetime] NULL,
	[BANDERA] [int] NULL,
 CONSTRAINT [PK_D_USUARIO_ASISTENCIA] PRIMARY KEY CLUSTERED 
(
	[CODIGO_ASISTENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[D_USUARIO_ASISTENCIA]  WITH CHECK ADD  CONSTRAINT [FK_D_USUARIO_ASISTENCIA_P_EMPRESA] FOREIGN KEY([EMPRESA])
REFERENCES [dbo].[P_EMPRESA] ([EMPRESA])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[D_USUARIO_ASISTENCIA] CHECK CONSTRAINT [FK_D_USUARIO_ASISTENCIA_P_EMPRESA]
GO

ALTER TABLE [dbo].[D_USUARIO_ASISTENCIA]  WITH CHECK ADD  CONSTRAINT [FK_D_USUARIO_ASISTENCIA_P_SUCURSAL] FOREIGN KEY([CODIGO_SUCURSAL])
REFERENCES [dbo].[P_SUCURSAL] ([CODIGO_SUCURSAL])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[D_USUARIO_ASISTENCIA] CHECK CONSTRAINT [FK_D_USUARIO_ASISTENCIA_P_SUCURSAL]
GO

